[tool.flake8_ruler]
max_line_length = 90

[tool.flake8_ruler.plugins]
"*" = ["+*"]

[tool.mypy]
files = ["flake8_ruler", "tests"]
python_version = 3.7
ignore_missing_imports = true
# follow_imports = "silent"
show_error_codes = true
allow_redefinition = true

# Settings making mypy checks harder.
# If something here produces too many false-positives,
# consider turning it off.
check_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true
# warn_unused_ignores = true
